src/components/Accordion/Accordion.vue
fixes default open bug when setting the prop `defaultOpen` to true would cause clicks on accordion to not show/hide the panel content
=> fix: default open on accordion

src/components/Modal/Modal.vue
- SE-31 Make modal accessible and enable keyboard events
- SE-33 CModal - content not visible if it exceeds the height of the page
Was slightly tricky trying to create focusTrap within modal - without the use of plugins, vue directives, [composables](https://www.telerik.com/blogs/how-to-trap-focus-modal-vue-3) etc. Focus handler method is simple and prevents focus (key board tabbing) leaving the modal element (otherwise it would tab through forms etc in the background)
=> Se 31 make modal accessible and enable keyboard events

src/components/Accordion/Accordion.vue
A requirement to have subscript character "R" was made. No such unicode character exists so HTML sub tags were needed. As the accordion title does not render HTML, nor do we want it to (natively at least) , I have added a customTitle slot. In column shoes this is called with HTML, that is then rendered in the custom slot, containing HTML.
=> feat: added custom title slot to accordion

src/components/AutoComplete/AutoComplete.vue, src/components/Checkbox/Checkbox.vue, src/components/FormElement/FormElement.vue, src/components/FormSection/FormSection.vue, src/components/RadioGroup/RadioGroup.vue, src/components/Table/Table.vue
To better support a reported troublesome resolution of 1366px several elements have been revised. In general, the layout has been improved to allow more space and become responsive when needed. The target snap point is "2xl" - 1560px IIRC.
Files changed, any why:
**Checkbox.vue & RadioGroup.vue** - these now accept a "labelOrder" prop that places the control input before the label, rather than after it. If the prop is omitted, the layout should render as before. 
**Table.vue** - this now accepts a "tableClass" prop allowing arbitrary classes to be passed in. For column shoes > loads, this solves the issue whereby the table is far too narrow to show its content. Scrollbars and overflow in general have been addressed also.
**FormSection.vue && FormElement.vue** - general styling …
=> Tscsc 601 UI fixes

src/components/FormSection/FormSection.vue, src/components/NumericInput/NumericInput.vue
Add prop to numeric input to hide spinner. This is done via CSS "appearance" as well as margin tweaks.
Also reduced font size of section headers to be slightly smaller.
=> feat: optionally hide numeric spinners

src/components/Accordion/Accordion.vue
Fix overflow issue. This needs overflow-y-auto to prevent lopping off select lists etc.
=> fix: fix overflow issue on smaller (v) screens

src/components/Resizable/Pane.vue, src/components/Resizable/Resizable.vue, src/components/Resizable/__stories__/Resizable.stories.mdx, src/index.js
Reactivated the dormant Resizable component. This is implemented in column shoes branch with the same name. This works differently to before and utilises the flex layout rather than fixed pixel sizes - although some fixed sizing is still needed.
Changes:
- No longer accepts max prop
- Accepts "primary" prop to set which pane (left or right) should have its "min" prop applied - this is due the the flex layout whereby we want free space filled.
- Flickering (perpetual resize loop) issues resolved
- Cases with no primary or no min set are handled
=> fix: revised and reactivated resizable

.gitignore, src/App.vue, src/components/Accordion/Accordion.vue, src/components/AutoComplete/AutoComplete.vue, src/components/Listbox/Listbox.vue, src/components/Resizable/Pane.vue, src/components/Resizable/Resizable.vue
Added transition effects to Autocomplete (contains Combobox) and Listbox. Note that the Accordion control has been revised to accept an overflowing object (the Listbox) and as such now toggles its own overflow state.
Latest branch of column shoes (fix/add-state-to-accordions) uses these revised widgets, should you wish to test them in context.
Added tweaks to solve some Resizable bugs that have been found also.
=> Se 44 add transition to listbox

src/components/AutoComplete/AutoComplete.vue, src/components/Listbox/Listbox.vue
Setting the transition to just opacity shows the top of the moving element too early. Adjusted to suit.
Also, first real test of new release please GitHub action.
=> fix: transition edits

src/components/Accordion/Accordion.vue, src/components/Listbox/Listbox.vue
Fixed the overflow and z-index issues when listbox is inside an accordion. Please check this in column shoes, for example.
=> fix: fixed listbox overflow issue with accordion

src/components/Resizable/Resizable.vue
Now that switching languages is available in column shoes, an error is raised on the resize event. Now wrapped in an if block.
=> fix: resize bug

src/components/Resizable/Resizable.vue
Revised z-index of separator as e2e tests reported this covering modal elements - modal z-index was recently changed.
Also set to redraw whilst dragging and not just when drag end.
=> fix: redraw on drag

src/components/Checkbox/Checkbox.vue, src/components/NumericInput/NumericInput.vue, src/components/TextInput/TextInput.vue
Added support for general override css to be passed in. Initially, this is to support custom table input styling for column shoe's load tables, as shown here:
=> feat: allow override css for inputs

src/components/Checkbox/Checkbox.vue, src/components/FormElement/FormElement.vue
Prevent checkout outline on mouse click but make sure that input is still focusable using tab key.
=> fix: remove checkout outline on click

src/components/Button/Button.vue, src/components/Table/Table.vue, src/components/Table/__stories__/Table.stories.mdx
The idea to enable subscript and superscript for table header label is to change how we are going to get the label from the columns prop. 
Instead of getting it as a string like we are getting it now:
[ { id: 'label1', label: 'label1' },  { id: 'label2', label: 'label2' } ] 
The proposed solution would be to get the label as an object with the html property that would be a string containing the needed order and sub or sup scripts:
[ 
{id: 'labelHtml', label: {html: `<span>V<sup>3</sup><sub>Ed</sub>[kN]</span>` }}
]
=> feat: enable label with subscript or superscript in table header

src/components/Accordion/Accordion.vue
Previously, the customTitle slot was inside the accordion toggle itself, causing issues when clickable items such as checkboxes were inside the slot. It is now outside.
=> fix: fixed incorrect placement of customTitle slot

src/components/NumericInput/NumericInput.vue, src/index.js, src/utils/units.js
Add conversions.
Note that if channel/channel dimensions are hidden, the bolt dimensions will be hidden as they have no context - they share the same channel dimension layer.
=> feat: add imperial units for inches, feet, lbf, lbf inches and kip

src/App.vue, src/components/NumericInput/NumericInput.vue, src/main.js
If a user clears a numeric input then the blank text is still parsed and a number is expected - this will oftentimes throw errors. Some clients want this behaviour but we do not want this by default. Therefore, the code has been revised to capture input changes and replace an empty field with these rules:
prop "nullable" exists = return null (as before)
prop "minimum" exists = return the minimum value
none of the above = return a zero
The key change here is that clients that want a null returned must now explicitily pass a nullable prop.
=> fix: default empty text to zero

src/components/RadioGroup/RadioGroup.vue
When radio group items drop due to not enough space, the x-padding goes with the item regardless leaving unwanted left padding. This fix removes this. Tested against both CiC and Column shoes projects.
OLD
NEW
=> fix: removed unwanted padding

src/components/Viewport/ViewportContainer.vue
Added a prop to force full width (ignoring responsive calculation). This is to support the titan task: 
https://crhleviat.atlassian.net/jira/software/c/projects/DCAT/boards/64?selectedIssue=DT-608
Please check this using titan as the callee project, branch:  DT-608-viewport-height
OLD:
NEW:
=> feat: added full width prop to viewport container

src/components/Listbox/Listbox.vue
Revised styling to better separateopen listbox from the page content. Shown here in a Column Shoes context...
OLD:
NEW:
=> feat: revise listbox styling

src/utils/units.ts
in terms of [LA-117](https://crhleviat.atlassian.net/browse/LA-117), where conversion from t/m3 to N/m3 is required
[LA-117]: https://crhleviat.atlassian.net/browse/LA-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add kg to N conversion

src/components/AutoComplete/AutoComplete.vue
The issue that we have currently on the design studio is that we are not triggering the API call to get projects that include input search and we are just stuck with the first 5 that we fetched. 
https://github.com/user-attachments/assets/0c23a8bf-ddb3-4169-a4de-001e3ef2740d
=> fix: issue with autocomplete input not triggering API calls on when typing
